### ISSUE TITLE
Default visibility distance in config is ignored

### ISSUE THREAD

**Issue by Frumple** [FancyMcPlugins/FancyHolograms#49]
Before version 2.0.2, any new holograms created would have their visibility distance set by `visibility_distance` in config.yml.

With version 2.0.2, new holograms are always created with a visibility distance of 20 regardless of what is set in the `visibility_distance` config setting.

Steps to Reproduce:
1. In config.yml, set `visibility_distance` to 60.
2. Restart the Minecraft server.
3. Create a new hologram with `/hologram create`.

Expected Result:
- New hologram should have a visibility distance of 60, both in-game and saved in holograms.yml.

Actual Result:
- New hologram has a visibility distance of 20, both in-game and saved in holograms.yml.

**Comment by OliverSchlueter** [comment]
Fixed in b76aa738a3b2d3468b6d30fd2b303a3002c41804 / [build #38](https://jenkins.fancyplugins.de/job/FancyHolograms/39/)

It will now look, if the visibility distance was overridden (via the command) and takes it, otherwise it takes the distance from the config.

Feel free to test it and let me know, if it works for you. Thank you for reporting this bug ❤️

**Comment by Frumple** [comment]
We've tested it out and it looks like this bug is fixed. Thanks!
